shutdown_costmaps: true #当move_base在不活动状态时,是否关掉costmap

controller_frequency: 5.0 #向底盘控制移动话题cmd_vel发送命令的频率.
controller_patience: 3.0

planner_frequency: 0.0 #全局规划器如果失败了的规划频率，0.0为只规划一次
planner_patience: 5.0

#机器人必须移动多远（以米计）才能被视为不摆动。
#如果出现摆动则说明全局规划失败，那么将在超时后执行恢复模块
oscillation_timeout: 5.0
oscillation_distance: 0.1

conservative_reset_dist: 0.1